import { NextRequest, NextResponse } from 'next/server'
import { authMiddleware } from '@/lib/middleware'
import { prisma } from '@/lib/db'
import { writeFile, mkdir } from 'fs/promises'
import { join } from 'path'
import { logError, logInfo } from '@/lib/logger'

export async function POST(request: NextRequest) {
  try {
    logInfo('Upload attempt started', 'UPLOAD')
    const user = authMiddleware(request)
    
    if (user instanceof NextResponse) {
      return user
    }

    const formData = await request.formData()
    const file = formData.get('file') as File
    const title = formData.get('title') as string
    const description = formData.get('description') as string
    const keywords = formData.get('keywords') as string
    const subject = formData.get('subject') as string

    if (!file) {
      return NextResponse.json(
        { error: 'No file provided' },
        { status: 400 }
      )
    }

    // Validate file type
    if (!file.type.startsWith('audio/')) {
      return NextResponse.json(
        { error: 'File must be an audio file' },
        { status: 400 }
      )
    }

    // Create uploads directory if it doesn't exist
    const uploadsDir = join(process.cwd(), 'public', 'uploads')
    await mkdir(uploadsDir, { recursive: true })

    // Generate unique filename
    const timestamp = Date.now()
    const filename = `${timestamp}-${file.name}`
    const filepath = join(uploadsDir, filename)

    // Save file
    const bytes = await file.arrayBuffer()
    const buffer = Buffer.from(bytes)
    await writeFile(filepath, buffer)

    // For now, we'll create a mock transcript
    // In a real application, you would integrate with a speech-to-text service
    const mockTranscript = `This is a mock transcript for the audio file "${file.name}". 
    In a production environment, this would be generated by a speech-to-text service like Google Speech-to-Text, 
    Amazon Transcribe, or OpenAI Whisper. The actual transcript would contain the spoken words from the audio file.`

    // Create content record
    const content = await prisma.content.create({
      data: {
        title: title || file.name,
        description: description || '',
        keywords: keywords || '',
        subject: subject || '',
        transcript: mockTranscript,
        audioUrl: `/uploads/${filename}`,
        audioDuration: 0, // You would calculate this from the actual audio file
        userId: user.userId,
        isPublished: false,
        isPublic: true
      },
      include: {
        user: {
          select: {
            id: true,
            name: true,
            email: true
          }
        }
      }
    })

    logInfo(`Content uploaded successfully: ${content.title}`, 'UPLOAD')
    
    return NextResponse.json({
      message: 'Content uploaded successfully',
      content
    })
  } catch (error) {
    logError(error, 'UPLOAD')
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}
