version: '3.8'

services:
  app:
    image: beheshtin-app
    build: .
    container_name: beheshtin-app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://beheshtin:securepassword123@db:5432/beheshtin_db
      - NEXTAUTH_SECRET=your-super-secret-key-change-this-in-production
      - NEXTAUTH_URL=https://beheshtin.com
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    container_name: beheshtin-db
    environment:
      - POSTGRES_DB=beheshtin_db
      - POSTGRES_USER=beheshtin
      - POSTGRES_PASSWORD=securepassword123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: beheshtin-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
