version: '3.8'

services:
  app:
    environment:
      - NEXTAUTH_URL=http://localhost:3000
    ports:
      - "3000:3000"

  nginx:
    ports:
      - "80:80"
    volumes:
      - ./nginx-local.conf:/etc/nginx/nginx.conf:ro

